name: API CI

on:
  push:
    branches: [ master ]
    paths:
      - 'app/services/api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'app/services/api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./app/services/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run linting
        run: uv run ruff check .

  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./app/services/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests
        run: uv run pytest tests/ -v
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}

      - name: Test API startup
        run: |
          uv run python -c "from finquest_api.main import app; print('API imports successfully')"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}

